apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server-dentist
spec:
  replicas: 1
  serviceName: "sql-server"
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-server-dentist-container
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: SA_PASSWORD
          ports:
            - containerPort: 1433
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server
spec:
  ports:
    - port: 1433
  selector:
    app: sql-server
